I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/letters.rpy", line 1, in script
    init python:
  File "game/letters.rpy", line 2, in <module>
    letter_1=Poem(
NameError: name 'Poem' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/letters.rpy", line 1, in script
    init python:
  File "/home/marquiskurt/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/marquiskurt/Desktop/renpy-6.99.14.3-sdk/renpy/python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/letters.rpy", line 2, in <module>
    letter_1=Poem(
NameError: name 'Poem' is not defined

Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid
Ren'Py 6.99.14.3.3347
 
Thu May 17 20:49:45 2018
